CREATE TABLE IF NOT EXISTS companies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  db_path TEXT NOT NULL,
  logo_path TEXT,
  created_at TEXT NOT NULL
);
